services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - struxt-net
    profiles:
      - dev
      - prod

  editor-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    scale: 2
    environment:
      - IS_DOCKER=true
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - PRIMARY_DB=${PRIMARY_DB}
      - UPLOAD_DIR=/uploads
    command: "node server/apiEntry.js"
    volumes:
      - ${UPLOAD_DIR}:/uploads
      - ${SITE_STORAGE_DIR}:/sites
    depends_on:
      - mariadb
      - nginx
    # ports:
    #   - "127.0.0.1:3000:3000"
    networks:
      - struxt-net
    profiles:
      - prod

  nginx:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "127.0.0.1:8181:81"
      - "443:443"
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    networks:
      - struxt-net
    profiles:
      - prod

volumes:
  mariadb_data:
  nginx_data:
  nginx_letsencrypt:

networks:
  struxt-net:
