services:
  web-host:
    image: ghcr.io/solociti/struxt:${VERSION:-latest}
    user: "1000:1000"
    restart: unless-stopped
    scale: 2
    env_file:
      - .env
    environment:
      - IS_DOCKER=true
      - UPLOAD_DIR=/uploads
      - CONTAINER_NAME=web-host
      - GEOTMPDIR=/uploads/geoip/tmp
      - GEODATADIR=/uploads/geoip/data
    command: "node server/publicHost.js"
    healthcheck:
      test: curl --fail http://localhost:3000/hc --max-time 5 --connect-timeout 5 || exit 1
      interval: 1m
      timeout: 6s
      retries: 5
      start_period: 30s
    labels:
      autoheal-app: true
    volumes:
      - ${UPLOAD_DIR}:/uploads
      - ${SITE_STORAGE_DIR}:/sites
      - .env:/app/.env:ro
    depends_on:
      - mongo
      - dragonfly
      - nginx
    networks:
      - struxt-net

  editor-api:
    image: ghcr.io/solociti/struxt:${VERSION:-latest}
    user: "1000:1000"
    restart: unless-stopped
    scale: 1
    env_file:
      - .env
    environment:
      - IS_DOCKER=true
      - UPLOAD_DIR=/uploads
      - CONTAINER_NAME=editor-api
      - GEOTMPDIR=/uploads/geoip/tmp
      - GEODATADIR=/uploads/geoip/data
    command: "node server/apiEntry.js"
    healthcheck:
      test: curl --fail http://localhost:3000/hc --max-time 5 --connect-timeout 5 || exit 1
      interval: 1m
      timeout: 6s
      retries: 5
      start_period: 30s
    labels:
      autoheal-app: true
    volumes:
      - ${UPLOAD_DIR}:/uploads
      - ${SITE_STORAGE_DIR}:/sites
      - .env:/app/.env:ro
    depends_on:
      - mongo
      - dragonfly
      - nginx
    networks:
      - struxt-net

  function-runner:
    build:
      context: .
      dockerfile: dev.Dockerfile
    user: "1000:1000"
    environment:
      - IS_DOCKER=true
      - CONTAINER_NAME=function-runner
    command: node --no-node-snapshot server/routinesEntry.js
    healthcheck:
      test: curl --fail http://localhost:3000/hc --max-time 5 --connect-timeout 5 || exit 1
      interval: 1m
      timeout: 6s
      retries: 5
      start_period: 30s
    depends_on:
      - dragonfly
    networks:
      - struxt-runner-net

  core:
    image: ghcr.io/solociti/struxt:${VERSION:-latest}
    user: "1000:1000"
    group_add:
      - ${DOCKER_GROUP_ID}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - IS_DOCKER=true
      - UPLOAD_DIR=/uploads
      - CONTAINER_NAME=core
      - GEOTMPDIR=/uploads/geoip/tmp
      - GEODATADIR=/uploads/geoip/data
    command: "node server/coreEntry.js"
    healthcheck:
      test: curl --fail http://localhost:3000/hc --max-time 5 --connect-timeout 5 || exit 1
      interval: 1m
      timeout: 6s
      retries: 5
      start_period: 30s
    labels:
      autoheal-app: true
    volumes:
      - ${UPLOAD_DIR}:/uploads
      - ${SITE_STORAGE_DIR}:/sites
      - ${BACKUP_DIR}:/backup
      - .env:/app/.env:ro
      # Mount Docker to run docker commands inside the container
      - /usr/bin/docker:/usr/bin/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - mongo
      - dragonfly
    networks:
      - struxt-net

  puppeteer:
    image: ghcr.io/solociti/struxt-puppeteer:${VERSION:-latest}
    user: "1000:1000"
    restart: unless-stopped
    scale: 1
    env_file:
      - .env
    environment:
      - IS_DOCKER=true
      - UPLOAD_DIR=/uploads
      - CONTAINER_NAME=puppeteer
      - GEOTMPDIR=/uploads/geoip/tmp
      - GEODATADIR=/uploads/geoip/data
    command: "node server/puppeteerEntry.js"
    healthcheck:
      test: curl --fail http://localhost:3000/hc --max-time 5 --connect-timeout 5 || exit 1
      interval: 1m
      timeout: 6s
      retries: 5
      start_period: 30s
    labels:
      autoheal-app: true
    volumes:
      - ${UPLOAD_DIR}:/uploads
      - ${SITE_STORAGE_DIR}:/sites
      - .env:/app/.env:ro
    depends_on:
      - mongo
      - dragonfly
      - nginx
    cap_add:
      - SYS_ADMIN
    networks:
      - struxt-net

  keycloak:
    image: ghcr.io/solociti/struxt-keycloak:${VERSION:-latest}
    restart: unless-stopped
    command: "start --optimized --http-enabled true"
    # healthcheck:
    #   test: curl --fail http://localhost:3000/health/ready --max-time 10 --connect-timeout 10 || exit 1
    #   interval: 1m
    #   timeout: 11s
    #   retries: 5
    #   start_period: 45s
    # labels:
    #   autoheal-app: true
    environment:
      - KC_HEALTH_ENABLED=true
      - KC_HOSTNAME=${KEYCLOAK_HOSTNAME}
      - KC_ADMIN_HOSTNAME=${KEYCLOAK_ADMIN_HOSTNAME}
      - KC_DB_URL=jdbc:mariadb://mariadb:3306/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KC_DB_POOL_MAX_SIZE=25
    ports:
      - "127.0.0.1:8443:8443"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:9000:9000"
    networks:
      - struxt-net
    depends_on:
      - mariadb
    profiles:
      - ${KEYCLOAK_DISABLED:-}

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - struxt-net
    profiles:
      - ${KEYCLOAK_DISABLED:-}

  autoheal:
    deploy:
      replicas: 1
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal-app
      AUTOHEAL_INTERVAL: 30s
      AUTOHEAL_START_PERIOD: 60s

    image: willfarrell/autoheal:latest
    network_mode: none
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
