services:
  mongo:
    image: mongo:8.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - struxt-net

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - struxt-net

  victoriametrics:
    image: victoriametrics/victoria-metrics:stable
    restart: unless-stopped
    ports:
      - "127.0.0.1:8428:8428"
    volumes:
      - ./config/victoria-metrics/victoria-metrics.yml:/etc/victoria-metrics/victoria-metrics.yml:ro
      - victoria_metrics_data:/victoria-metrics-data
    command:
      - -selfScrapeInterval=60s
      - -storageDataPath=/victoria-metrics-data
      - -promscrape.config=/etc/victoria-metrics/victoria-metrics.yml
      - -memory.allowedPercent=20
    networks:
      - struxt-net

  grafana:
    image: grafana/grafana:main
    restart: unless-stopped
    environment:
      - GF_PLUGINS_PREINSTALL=victoriametrics-metrics-datasource
    ports:
      - "127.0.0.1:3030:3000"
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./config/grafana:/etc/grafana/provisioning:ro"
    networks:
      - struxt-net

  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data
      - ./config/dragonFlyFlags.txt:/flags.txt
    networks:
      - struxt-net
    command: "dragonfly --flagfile=/flags.txt"

  nginx:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "127.0.0.1:81:81"
      - "443:443"
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    networks:
      - struxt-net

volumes:
  dragonflydata:
  grafana_data:
  mariadb_data:
  mongo_data:
  nginx_data:
  nginx_letsencrypt:
  victoria_metrics_data:

networks:
  struxt-net:
