services:
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - struxt-net
    profiles:
      - dev
      - prod

  editor-api:
    image: ./Dockerfile
    environment:
      - IS_DOCKER=true
    command: "node server/apiEntry.js"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mariadb
      - nginx
    # ports:
    #   - "127.0.0.1:3000:3000"
    networks:
      - struxt-net
    profiles:
      - prod

  nginx:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx_date:/data
      - nginx_letsencrypt:/etc/letsencrypt
    networks:
      - struxt-net
    profiles:
      - prod

volumes:
  mariadb_data:
  nginx_data:
  nginx_letsencrypt:

networks:
  struxt-net:
