{
 "title": "Basic Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Site Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Custom Request Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (project_id) (rate(struxt_site_requests[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Custom Request Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (status) (rate(struxt_site_requests[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Browsers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(browser) (struxt_site_requests_devices)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(os) (struxt_site_requests_devices)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Location",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(country) (struxt_site_requests_geolocation)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Duration (Latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "avg(rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "HTTP Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(http_request_duration_seconds_count{status_code=~\"5..|4..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90th Percentile Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Mem {{job}}" },
    { "expr": "process_heap_bytes", "legendFormat": "Heap {{job}}" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Node.js Garbage Collection Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, kind) (rate(nodejs_gc_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node.js Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_mean_seconds ",
     "legendFormat": "Average {{job}}"
    },
    {
     "expr": "nodejs_eventloop_lag_p90_seconds ",
     "legendFormat": "90th {{job}}"
    },
    {
     "expr": "nodejs_eventloop_lag_p99_seconds ",
     "legendFormat": "99th {{job}}"
    }
   ]
  }
 ]
}