// This file is generated by the createSchema.js script. Do not edit it manually.

export interface db__knex_migrations {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  id: number;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `YES`   */
  name: string | null;
  /**
   * Type: `int(11)`
   *
   * Default: `null`
   *
   * Nullable: `YES`   */
  batch: number | null;
  /**
   * Type: `timestamp`
   *
   * Default: `null`
   *
   * Nullable: `YES`   */
  migration_time: Date | null;
}

export interface db__knex_migrations_lock {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  index: number;
  /**
   * Type: `int(11)`
   *
   * Default: `null`
   *
   * Nullable: `YES`   */
  is_locked: number | null;
}

export interface db_domains {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  id: number;
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `MUL`   */
  site_id: number;
  /**
   * Type: `varchar(36)`
   *
   * Default: `null`
   *
   * Nullable: `YES`
   *
   * Key: `MUL`   */
  updated_by: string | null;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `UNI`   */
  domain: string;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  site_env: string;
  /**
   * Type: `int(1)`
   *
   * Default: `1`
   *
   * Nullable: `NO`   */
  enabled: number;
  /**
   * Type: `int(1)`
   *
   * Default: `0`
   *
   * Nullable: `NO`   */
  is_primary: number;
  /**
   * Type: `tinyint(1)`
   *
   * Default: `0`
   *
   * Nullable: `NO`   */
  dns_verified: boolean;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  created_at: Date;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  updated_at: Date;
}

export interface db_domains_history {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  __id: number;
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  id: number;
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  site_id: number;
  /**
   * Type: `varchar(36)`
   *
   * Default: `null`
   *
   * Nullable: `YES`
   *
   * Key: `MUL`   */
  updated_by: string | null;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `UNI`   */
  domain: string;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  site_env: string;
  /**
   * Type: `int(1)`
   *
   * Default: `1`
   *
   * Nullable: `NO`   */
  enabled: number;
  /**
   * Type: `int(1)`
   *
   * Default: `0`
   *
   * Nullable: `NO`   */
  is_primary: number;
  /**
   * Type: `tinyint(1)`
   *
   * Default: `0`
   *
   * Nullable: `NO`   */
  dns_verified: boolean;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  created_at: Date;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  updated_at: Date;
}

export interface db_id_counters {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  id: number;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `UNI`   */
  name: string;
  /**
   * Type: `int(11)`
   *
   * Default: `0`
   *
   * Nullable: `NO`   */
  value: number;
}

export interface db_project_settings {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  id: number;
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `MUL`   */
  site_id: number;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  site_env: string;
  /**
   * Type: `tinyint(1)`
   *
   * Default: `0`
   *
   * Nullable: `NO`   */
  force_ssl: boolean;
  /**
   * Type: `tinyint(1)`
   *
   * Default: `0`
   *
   * Nullable: `NO`   */
  hsts: boolean;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `YES`   */
  updated_by: string | null;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  created_at: Date;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  updated_at: Date;
}

export interface db_project_settings_history {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  _id: number;
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `MUL`   */
  site_id: number;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  site_env: string;
  /**
   * Type: `tinyint(1)`
   *
   * Default: `0`
   *
   * Nullable: `NO`   */
  force_ssl: boolean;
  /**
   * Type: `tinyint(1)`
   *
   * Default: `0`
   *
   * Nullable: `NO`   */
  hsts: boolean;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `YES`   */
  updated_by: string | null;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  created_at: Date;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  updated_at: Date;
}

export interface db_pub_form_attachments {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  id: number;
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `YES`
   *
   * Key: `MUL`   */
  submission_id: number | null;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  file_name: string;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  original_name: string;
  /**
   * Type: `varchar(255)`
   *
   * Default: `pending`
   *
   * Nullable: `NO`   */
  av_status: string;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  av_result: string;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  created_at: Date;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  updated_at: Date;
}

export interface db_pub_form_settings {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  id: number;
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `YES`
   *
   * Key: `MUL`   */
  site_id: number | null;
  /**
   * Type: `varchar(15)`
   *
   * Default: `production`
   *
   * Nullable: `NO`   */
  site_env: string;
  /**
   * Type: `varchar(50)`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  form_name: string;
  /**
   * Type: `varbinary(1)`
   *
   * Default: `1`
   *
   * Nullable: `NO`   */
  legacy_enabled: string;
  /**
   * Type: `tinyint(1)`
   *
   * Default: `1`
   *
   * Nullable: `NO`   */
  enabled: boolean;
  /**
   * Type: `varbinary(1)`
   *
   * Default: `1`
   *
   * Nullable: `NO`   */
  legacy_send_email: string;
  /**
   * Type: `tinyint(1)`
   *
   * Default: `0`
   *
   * Nullable: `YES`   */
  send_email: boolean | null;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  email_to: string;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  email_subject: string;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  created_at: Date;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  updated_at: Date;
}

export interface db_pub_form_submissions {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  id: number;
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `YES`
   *
   * Key: `MUL`   */
  site_id: number | null;
  /**
   * Type: `varchar(15)`
   *
   * Default: `production`
   *
   * Nullable: `NO`   */
  site_env: string;
  /**
   * Type: `varchar(50)`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  form_name: string;
  /**
   * Type: `longtext`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  contents: string;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  ip_address: string;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  user_agent: string;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  sent_email_id: string;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  created_at: Date;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  updated_at: Date;
}

export interface db_pub_form_validation {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  id: number;
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `YES`
   *
   * Key: `MUL`   */
  site_id: number | null;
  /**
   * Type: `varchar(15)`
   *
   * Default: `production`
   *
   * Nullable: `NO`   */
  site_env: string;
  /**
   * Type: `varchar(50)`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  form_name: string;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  field_name: string;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  type: string;
  /**
   * Type: `tinyint(1)`
   *
   * Default: `0`
   *
   * Nullable: `NO`   */
  required: boolean;
  /**
   * Type: `tinyint(1)`
   *
   * Default: `0`
   *
   * Nullable: `NO`   */
  archived: boolean;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  created_at: Date;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  updated_at: Date;
}

export interface db_public_site_stats {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  id: number;
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `0`
   *
   * Nullable: `NO`   */
  site_id: number;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  method: string;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  hostname: string;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  url: string;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  path: string;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  ip: string;
  /**
   * Type: `varchar(500)`
   *
   * Nullable: `NO`   */
  user_agent: string;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  referrer: string;
  /**
   * Type: `int(3)`
   *
   * Default: `0`
   *
   * Nullable: `NO`   */
  status: number;
  /**
   * Type: `int(15)`
   *
   * Default: `0`
   *
   * Nullable: `NO`   */
  response_time_ms: number;
  /**
   * Type: `datetime`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  created_at: Date;
}

export interface db_sessions {
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`   */
  sid: string;
  /**
   * Type: `longtext`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  sess: string;
  /**
   * Type: `datetime`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `MUL`   */
  expired: Date;
}

export interface db_site_assets {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  id: number;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `UNI`   */
  file_path: string;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  original_name: string;
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `MUL`   */
  site_id: number;
  /**
   * Type: `varchar(36)`
   *
   * Default: `null`
   *
   * Nullable: `YES`
   *
   * Key: `MUL`   */
  updated_by: string | null;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  created_at: Date;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  updated_at: Date;
}

export interface db_site_assets_history {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  __id: number;
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  id: number;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `UNI`   */
  file_path: string;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  original_name: string;
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  site_id: number;
  /**
   * Type: `varchar(36)`
   *
   * Default: `null`
   *
   * Nullable: `YES`
   *
   * Key: `MUL`   */
  updated_by: string | null;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  created_at: Date;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  updated_at: Date;
}

export interface db_site_publish_info {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  id: number;
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `0`
   *
   * Nullable: `NO`
   *
   * Key: `MUL`   */
  site_id: number;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  site_env: string;
  /**
   * Type: `varchar(255)`
   *
   * Nullable: `NO`   */
  screenshot_url: string;
  /**
   * Type: `datetime`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  published_at: Date;
  /**
   * Type: `varchar(36)`
   *
   * Default: `null`
   *
   * Nullable: `YES`
   *
   * Key: `MUL`   */
  published_by: string | null;
}

export interface db_sites {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  id: number;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  name: string;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  description: string;
  /**
   * Type: `varchar(36)`
   *
   * Default: `null`
   *
   * Nullable: `YES`
   *
   * Key: `MUL`   */
  updated_by: string | null;
  /**
   * Type: `longtext`
   *
   * Default: `'{}'`
   *
   * Nullable: `NO`   */
  project: string;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  created_at: Date;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  updated_at: Date;
}

export interface db_sites_history {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  __id: number;
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  id: number;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  name: string;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  description: string;
  /**
   * Type: `varchar(36)`
   *
   * Default: `null`
   *
   * Nullable: `YES`
   *
   * Key: `MUL`   */
  updated_by: string | null;
  /**
   * Type: `longtext`
   *
   * Default: `'{}'`
   *
   * Nullable: `NO`   */
  project: string;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  created_at: Date;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  updated_at: Date;
}

export interface db_user_roles {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  id: number;
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `YES`
   *
   * Key: `MUL`   */
  site_id: number | null;
  /**
   * Type: `varchar(255)`
   *
   * Default: `view`
   *
   * Nullable: `NO`   */
  action: string;
  /**
   * Type: `int(1)`
   *
   * Default: `0`
   *
   * Nullable: `NO`   */
  enabled: number;
  /**
   * Type: `varchar(36)`
   *
   * Default: `null`
   *
   * Nullable: `YES`
   *
   * Key: `MUL`   */
  updated_by: string | null;
  /**
   * Type: `varchar(36)`
   *
   * Default: `null`
   *
   * Nullable: `YES`
   *
   * Key: `MUL`   */
  user_id: string | null;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  created_at: Date;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  updated_at: Date;
}

export interface db_user_roles_history {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  __id: number;
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  id: number;
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `YES`   */
  site_id: number | null;
  /**
   * Type: `varchar(255)`
   *
   * Default: `view`
   *
   * Nullable: `NO`   */
  action: string;
  /**
   * Type: `int(1)`
   *
   * Default: `0`
   *
   * Nullable: `NO`   */
  enabled: number;
  /**
   * Type: `varchar(36)`
   *
   * Default: `null`
   *
   * Nullable: `YES`
   *
   * Key: `MUL`   */
  updated_by: string | null;
  /**
   * Type: `varchar(36)`
   *
   * Default: `null`
   *
   * Nullable: `YES`
   *
   * Key: `MUL`   */
  user_id: string | null;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  created_at: Date;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  updated_at: Date;
}

export interface db_users {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  id: number;
  /**
   * Type: `varchar(36)`
   *
   * Default: `null`
   *
   * Nullable: `YES`
   *
   * Key: `UNI`   */
  uuid: string | null;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `UNI`   */
  email: string;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  display_name: string;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  created_at: Date;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  updated_at: Date;
}

export interface db_users_history {
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`
   *
   * Key: `PRI`
   *
   * Extra: `auto_increment`   */
  __id: number;
  /**
   * Type: `int(10) unsigned`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  id: number;
  /**
   * Type: `varchar(36)`
   *
   * Default: `null`
   *
   * Nullable: `YES`   */
  uuid: string | null;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  email: string;
  /**
   * Type: `varchar(255)`
   *
   * Default: `null`
   *
   * Nullable: `NO`   */
  display_name: string;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  created_at: Date;
  /**
   * Type: `timestamp`
   *
   * Default: `current_timestamp()`
   *
   * Nullable: `NO`   */
  updated_at: Date;
}
