import { Model, ModelAction, UserModelAction } from "common/models/Model";
import { DeepPartial, mergeDeep } from "common/models/utils";
import { EnvironmentTypes } from "./Environment";

/**
 * One document per `projectId + siteEnv`. Stores an X25519 keypair for a project.
 * The private key is AES-256-GCM encrypted with SECRETS_MASTER_KEY and never returned by any API.
 */
export class ProjectKeyModel extends Model {
  public projectId: string = "";
  public siteEnv: EnvironmentTypes = "staging";

  public publicKeyHex: string = "";

  public encryptedPrivateKeyHex: string = "";

  /**
   * Created timestamp.
   *
   * Attribution to user is not needed, because this is autogenerated on demand.
   */
  public created: Omit<ModelAction, "active"> = {
    date: Math.floor(Date.now() / 1000),
  };

  constructor(data?: DeepPartial<ProjectKeyModel>) {
    super();
    if (data) {
      this.update(data);
    }
  }

  /**
   * Merges partial data into this instance.
   *
   * @param data
   */
  update(data: DeepPartial<ProjectKeyModel>) {
    mergeDeep(this, data);
  }

  clone(): ProjectKeyModel {
    return new ProjectKeyModel(JSON.parse(JSON.stringify(this)));
  }
}

/**
 * One document per `projectId + siteEnv + key`. Stores a client-encrypted secret value.
 * The encrypted value is never decrypted by the API — only at Fission deploy time.
 */
export class ProjectSecretModel extends Model {
  public projectId: string = "";
  public siteEnv: EnvironmentTypes = "staging";
  /**
   * Stable identifier matching `VariableState.uuid`.
   */
  public varUuid: string = "";
  /**
   * The variable name (key). May change on rename — `varUuid` is the stable lookup key.
   */
  public key: string = "";

  public ephemeralPublicKeyHex: string = "";

  public encryptedValueHex: string = "";

  public created: Omit<UserModelAction, "active"> = {
    date: Math.floor(Date.now() / 1000),
    userId: "",
    displayName: "",
  };

  public updated: Omit<UserModelAction, "active"> = {
    date: Math.floor(Date.now() / 1000),
    userId: "",
    displayName: "",
  };

  constructor(data?: DeepPartial<ProjectSecretModel>) {
    super();
    if (data) {
      this.update(data);
    }
  }

  /**
   * Merges partial data into this instance.
   *
   * @param data
   */
  update(data: DeepPartial<ProjectSecretModel>) {
    mergeDeep(this, data);
  }

  clone(): ProjectSecretModel {
    return new ProjectSecretModel(JSON.parse(JSON.stringify(this)));
  }
}
