import { AiPilotAgentIds } from "common/api/aiPilot/aiPilotEvents";
import { Model, UserModelAction } from "../Model";
import { DeepPartial, mergeDeep } from "../utils";

export class ChatMessage extends Model {
  /**
   * The unique identifier for the chat message.
   */
  public uuid = "";

  /**
   * The ID of the chat this message belongs to.
   */
  public chatId = "";

  /**
   * Indicates if the message is from the user or the AI.
   * true for user messages, false for AI messages.
   */
  public isUserMessage = true;

  /**
   * If this is a user message, this is the ID of the user who sent it.
   * if this is an AI message, the userId and displayName will be empty.
   */
  public created: Omit<UserModelAction, "active"> = {
    date: Math.floor(Date.now() / 1000),
    userId: "",
    displayName: "",
  };

  constructor(data?: DeepPartial<ChatMessage>) {
    super();

    if (data) {
      this.update(data);
    }
  }

  update(data: DeepPartial<ChatMessage>) {
    mergeDeep(this, data);
  }

  clone(): ChatMessage {
    const data = JSON.parse(JSON.stringify(this));
    return new ChatMessage(data);
  }

  static fromData(
    data: DeepPartial<ChatMessage>
  ): UserChatMessage | AiChatMessage {
    if (typeof data.isUserMessage === "boolean" && !data.isUserMessage) {
      return new AiChatMessage(data);
    }
    return new UserChatMessage(data);
  }
}

/**
 * Represents a message sent by a user in the AI Pilot chat.
 */
export class UserChatMessage extends ChatMessage {
  /**
   * The content of the message sent by the user.
   */
  public content = "";

  public isUserMessage = true;

  constructor(data?: DeepPartial<UserChatMessage>) {
    super(data);

    if (data) {
      this.update(data);
    }
  }

  update(data: DeepPartial<UserChatMessage>) {
    mergeDeep(this, data);
  }

  clone(): UserChatMessage {
    const data = JSON.parse(JSON.stringify(this));
    return new UserChatMessage(data);
  }
}

/**
 * Represents a message generated by the AI in the AI Pilot chat.
 */
export class AiChatMessage extends ChatMessage {
  public isUserMessage = false;

  /**
   * The contents of the message generated by the AI.
   *
   * This includes any resources requested by the AI.
   */
  public contents: AiChatContents[] = [];

  /**
   * Additional metadata about the AI response,
   * such as processing time or model used.
   */
  public metadata: {
    model: string;
    temperature: number;
  } = {
    model: "",
    temperature: 0,
  };

  constructor(data?: DeepPartial<AiChatMessage>) {
    super(data);

    if (data) {
      this.update(data);
    }
  }

  update(data: DeepPartial<AiChatMessage>) {
    mergeDeep(this, data, ["contents"]);

    if (data?.contents) {
      this.contents = data.contents.map((c) => {
        const original: AiChatContents = {
          agentId: "supervisor",
          contentId: "",
          content: "",
          category: "unknown",
          msgType: "ai",
          action: "",
          totalTokens: 0,
        };

        return { ...original, ...c };
      });
    }
  }

  clone(): AiChatMessage {
    const data = JSON.parse(JSON.stringify(this));
    return new AiChatMessage(data);
  }

  getMergedContent(): AiChatContents[] {
    const list: AiChatContents[] = [];
    let current: AiChatContents | null = null;

    for (const content of this.contents) {
      if (content.category === "message") {
        if (current) {
          // merge message contents
          current.content = [current.content, content.content].join("");
          current.totalTokens += content.totalTokens;
        } else {
          current = { ...content };
          list.push(current);
        }
      } else {
        current = null;
        list.push(content);
      }
    }

    return list;
  }
}

/**
 * Represents the contents of a message or resource in the AI Pilot chat.
 */
export interface AiChatContents {
  agentId: AiPilotAgentIds;

  /**
   * This id can be used when debugging to find the raw tool call output.
   */
  contentId: string;

  /**
   * The content of the message or resource.
   */
  content: string;

  /**
   * The message category, this is determined from the lang_chain id.
   */
  category: "message" | "tool_call" | "resource" | "unknown";

  /**
   * The specific action or operation identifier.
   *
   * For tool calls, this could be something like
   * transfer_back_to_supervisor or transfer_to_code_agent
   *
   * We can use this to determine what label to show for the current generating spinner.
   */
  action: string;

  msgType:
    | "function"
    | "human"
    | "ai"
    | "generic"
    | "developer"
    | "system"
    | "tool"
    | "remove";

  /**
   * The number of tokens used in this message or resource.
   */
  totalTokens: number;
}
