apiVersion: 1

datasources:
  - name: "VictoriaMetrics"
    type: "victoriametrics-metrics-datasource"
    access: "proxy"
    url: "http://victoriametrics:8428"
    jsonData:
      httpMethod: "POST"
      timeInterval: "1m"
      vmuiUrl: "http://localhost:8428"
    isDefault: true
    editable: false
    version: 1
