import { ObserverSetup } from "common/api/observer";
import { ServerEventsQuery, ServerToClientEvents } from "common/api/websocket";
import {
  deStructureError,
  ErrorNames,
  HTTPStatus,
} from "common/custom-error/custom-error";
import { CurrentUserModel } from "common/models/user/CurrentUserModel";
import { userFromReq } from "server/api/auth/userFromReq";
import { SocketWithEvents } from "./setupWs";

interface ObserverEvent<Setup extends ObserverSetup> {
  /**
   * The current logged in user.
   */
  user: CurrentUserModel;

  /**
   * The event name that the client is subscribed to.
   */
  event: keyof ServerToClientEvents;

  socket: SocketWithEvents;

  /**
   * The client ID that is registered for this event.
   *
   * This id is generated by the client, and is only unique within the current session. Uniqueness can't be guaranteed.
   */
  id: number;

  /**
   * Send a socket.io message to the client on this channel.
   *
   * @returns
   */
  send: (
    ...args: Parameters<ServerToClientEvents[keyof ServerToClientEvents]>
  ) => void;

  /**
   * Send a request to the client on a specific channel.
   *
   * The client should respond to this request with a callback.
   *
   * @param channel
   * @param args
   * @returns
   */
  sendRequest: <C extends keyof Setup["serverRequests"]>(
    channel: C,
    ...args: Parameters<Setup["serverRequests"][C]>
  ) => ReturnType<Setup["serverRequests"][C]>;
}

/**
 * The return value of the observer callback.
 */
interface ObserverCallbackResult<
  cRequests extends ObserverSetup["clientRequests"]
> {
  onUnregister: () => void;

  /**
   * A request sent from the client to the server.
   */
  onClientRequests?: cRequests;
}

/**
 * Callback for the observer.
 */
type ObserverCallback<Q, Setup extends ObserverSetup> = (
  event: ObserverEvent<Setup>,
  query: Q
) => Promise<ObserverCallbackResult<Setup["clientRequests"]>>;

/**
 * Keeps track of observers for different events.
 */
const observers: {
  [K in keyof ServerToClientEvents]?: ObserverCallback<
    ServerEventsQuery[K],
    any
  >;
} = {};

/**
 * Setup the events required for the observers.
 *
 * @param socket
 */
export async function onConnection(socket: SocketWithEvents) {
  const user = await userFromReq(socket.request);

  // prevent observers from being registered if the user is not authenticated
  if (!user.isAuthenticated()) {
    return;
  }

  const activeObservers: Record<
    number,
    { cleanup: Function[]; result: ObserverCallbackResult<{}> }
  > = {};

  socket.on("subscribe:init", async (eventName, id, query, callback) => {
    if (activeObservers[id]) {
      console.warn(`ID ${id} is already in use. Skipping subscription.`);
      return;
    }

    activeObservers[id] = {
      cleanup: [],
      result: null as any,
    };

    if (observers[eventName]) {
      const observerCb = observers[eventName];

      try {
        const observerResult = await observerCb(
          {
            event: eventName,
            id,
            user,
            socket,
            send: (
              ...args: Parameters<ServerToClientEvents[typeof eventName]>
            ) => {
              if (!socket.connected || !activeObservers[id]) {
                return;
              }

              socket.emit(eventName, ...args);
            },
            sendRequest: (channel, data) => {
              return new Promise((resolve, reject) => {
                if (!activeObservers[id]) {
                  reject(new Error("Observer is not active"));
                  return;
                }

                socket.emit(
                  `${eventName}:req:${String(channel)}` as any,
                  data,
                  (response: any) => {
                    if (!response || response.error) {
                      reject(
                        deStructureError(
                          response.error,
                          "Unknown error from server"
                        )
                      );
                      return;
                    }

                    resolve(response);
                  }
                );
              });
            },
          },
          query
        );

        activeObservers[id].result = observerResult;
        activeObservers[id].cleanup.push(observerResult.onUnregister);

        // register any client request channels
        if (observerResult.onClientRequests) {
          for (const channel in observerResult.onClientRequests) {
            const callback = observerResult.onClientRequests[channel];

            const cb = async (
              request: any,
              responseCb: (...args: any[]) => void
            ) => {
              try {
                const response = await callback(request);
                responseCb(response);
              } catch (error: any) {
                responseCb({
                  success: false,
                  error: {
                    name: error.name,
                    message: error.message,
                    status: error.status || 500,
                  },
                });
              }
            };

            socket.on(`${eventName}:req:${channel}` as any, cb);
            activeObservers[id].cleanup.push(() => {
              socket.off(`${eventName}:req:${channel}` as any, cb);
            });
          }
        }

        callback({
          success: true,
          error: null,
        });
      } catch (err: unknown) {
        if (err instanceof Error) {
          callback({
            success: false,
            error: {
              name: err.name,
              message: err.message,
              status: (err.status as HTTPStatus) || 500,
            },
          });
        } else {
          callback({
            success: false,
            error: {
              name: ErrorNames.ObserverError,
              message: "An error occurred while setting up the observer.",
              status: 500,
            },
          });
        }
      }
    } else {
      console.warn(`No observer registered for event: ${eventName}`);
    }
  });

  socket.on(
    "subscribe:stop",
    (_event: keyof ServerToClientEvents, id: number) => {
      // remove the ID from the active IDs set
      if (activeObservers[id]) {
        activeObservers[id].cleanup.forEach((cleanupFn) => cleanupFn());
        delete activeObservers[id];
      }
    }
  );

  socket.on("disconnect", () => {
    // Clean up all active observers on disconnect
    for (const id in activeObservers) {
      activeObservers[id].cleanup.forEach((cleanupFn) => cleanupFn());
      delete activeObservers[id];
    }
  });
}

/**
 * Register an observer for a specific event.
 *
 * If a user is not authenticated, the observer setup callback won't run.
 *
 * @param eventName
 * @param setupCallback If a error is thrown, the observer will not be registered.
 */
export function registerObserver<Setup extends ObserverSetup>(
  eventName: keyof ServerToClientEvents,
  setupCallback: ObserverCallback<ServerEventsQuery[typeof eventName], Setup>
) {
  if (!observers[eventName]) {
    observers[eventName] = setupCallback as ObserverCallback<
      ServerEventsQuery[typeof eventName],
      any
    >;
  } else {
    console.warn(`Observer for event ${eventName} already exists.`);
  }
}
