import { ServerEventsQuery, ServerToClientEvents } from "common/api/websocket";
import { ErrorNames, HTTPStatus } from "common/custom-error/custom-error";
import { CurrentUserModel } from "common/models/user/CurrentUserModel";
import { userFromReq } from "server/api/auth/userFromReq";
import { SocketWithEvents } from "./setupWs";

interface ObserverEvent {
  /**
   * The current logged in user.
   */
  user: CurrentUserModel;

  /**
   * The event name that the client is subscribed to.
   */
  event: keyof ServerToClientEvents;

  /**
   * The client ID that is registered for this event.
   *
   * This id is generated by the client, and is only unique within the current session. Uniqueness can't be guaranteed.
   */
  id: number;

  /**
   * Send a socket.io message to the client on this channel.
   *
   * @returns
   */
  send: (
    ...args: Parameters<ServerToClientEvents[keyof ServerToClientEvents]>
  ) => void;
}

/**
 * The return value of the observer callback.
 */
interface ObserverCallbackResult {
  onUnregister: () => void;
}

/**
 * Callback for the observer.
 */
type ObserverCallback<Q> = (
  event: ObserverEvent,
  query: Q
) => Promise<ObserverCallbackResult>;

/**
 * Keeps track of observers for different events.
 */
const observers: {
  [K in keyof ServerToClientEvents]?: ObserverCallback<ServerEventsQuery[K]>;
} = {};

/**
 * Setup the events required for the observers.
 *
 * @param socket
 */
export async function onConnection(socket: SocketWithEvents) {
  const user = await userFromReq(socket.request);

  // prevent observers from being registered if the user is not authenticated
  if (!user.isAuthenticated()) {
    return;
  }

  const activeObservers: Record<number, ObserverCallbackResult> = {};

  socket.on("subscribe:init", async (eventName, id, query, callback) => {
    if (activeObservers[id]) {
      console.warn(`ID ${id} is already in use. Skipping subscription.`);
      return;
    }

    if (observers[eventName]) {
      const observerCb = observers[eventName];

      try {
        activeObservers[id] = await observerCb(
          {
            event: eventName,
            id,
            user,
            send: (
              ...args: Parameters<ServerToClientEvents[typeof eventName]>
            ) => {
              if (!socket.connected || !activeObservers[id]) {
                return;
              }

              socket.emit(eventName, ...args);
            },
          },
          query
        );

        callback({
          success: true,
          error: null,
        });
      } catch (err: unknown) {
        if (err instanceof Error) {
          callback({
            success: false,
            error: {
              name: err.name,
              message: err.message,
              status: (err.status as HTTPStatus) || 500,
            },
          });
        } else {
          callback({
            success: false,
            error: {
              name: ErrorNames.ObserverError,
              message: "An error occurred while setting up the observer.",
              status: 500,
            },
          });
        }
      }
    } else {
      console.warn(`No observer registered for event: ${eventName}`);
    }
  });

  socket.on(
    "subscribe:stop",
    (_event: keyof ServerToClientEvents, id: number) => {
      // remove the ID from the active IDs set
      if (activeObservers[id]) {
        activeObservers[id].onUnregister();
        delete activeObservers[id];
      }
    }
  );

  socket.on("disconnect", () => {
    // Clean up all active observers on disconnect
    for (const id in activeObservers) {
      activeObservers[id].onUnregister();
      delete activeObservers[id];
    }
  });
}

/**
 * Register an observer for a specific event.
 *
 * If a user is not authenticated, the observer setup callback won't run.
 *
 * @param eventName
 * @param setupCallback If a error is thrown, the observer will not be registered.
 */
export function registerObserver(
  eventName: keyof ServerToClientEvents,
  setupCallback: ObserverCallback<ServerEventsQuery[typeof eventName]>
) {
  if (!observers[eventName]) {
    observers[eventName] = setupCallback;
  } else {
    console.warn(`Observer for event ${eventName} already exists.`);
  }
}
