// @ts-check
import knexDb from "knex";
import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import config from "../knexfile.js";

const knex = knexDb(config);

/**
 * Create interfaces for all tables in the database
 */
export async function createTsSchemaInterfaces() {
  while (true) {
    try {
      await knex.select(1);
      break;
    } catch (error) {
      await new Promise((resolve) => setTimeout(resolve, 250));
    }
  }

  const tsFilePath = "common/models/database.ts";
  let tsFile = `// This file is generated by the createSchema.js script. Do not edit it manually.\n\n`;

  const tables = await knex.raw("SHOW TABLES");

  for (const tableRow of tables[0]) {
    const [key] = Object.keys(tableRow);
    const table = tableRow[key];

    tsFile += `export interface db_${table} {\n`;

    const columns = await knex.raw(`SHOW COLUMNS FROM ${table}`);

    for (const col of columns[0]) {
      const column = col.Field;
      const type = col.Type;
      let colType = "string";

      if (type.startsWith("int")) {
        colType = "number";
      } else if (type.startsWith("varchar") || type.startsWith("text")) {
        colType = "string";
      } else if (type.startsWith("datetime") || type.startsWith("timestamp")) {
        colType = "Date";
      } else if (type.startsWith("tinyint")) {
        colType = "boolean";
      }

      if (col.Null === "YES") {
        colType += " | null";
      }

      const commentLines = [
        col.Comment || "",
        `Type: \`${col.Type}\``,
        `Default: \`${col.Default}\``,
        `Nullable: \`${col.Null}\``,
        `Key: \`${col.Key}\``,
        `Extra: \`${col.Extra}\``,
      ]
        .filter((val) => !!val && !val.endsWith(": ``"))
        .map((val) => `   * ${val}`)
        .join("\n   *\n");

      tsFile += `  /**\n`;
      tsFile += commentLines;
      tsFile += `   */\n`;
      tsFile += `  ${column}: ${colType};\n`;
    }

    tsFile += `}\n\n`;
  }

  // remove the last new line
  tsFile = tsFile.slice(0, -1);

  console.log("Updating database.ts file");
  console.log("Path: ", tsFilePath);

  const currentFile = existsSync(tsFilePath)
    ? await readFile(tsFilePath, "utf-8")
    : "";
  if (currentFile !== tsFile) {
    console.log("Updated file");
    await writeFile(tsFilePath, tsFile, "utf-8");
  } else {
    console.log("No changes to database.ts file");
  }
}

createTsSchemaInterfaces()
  .then(() => {
    knex.destroy();
  })
  .catch((err) => {
    console.error("Error creating schema interfaces:", err);
    knex.destroy();
    process.exit(1);
  });
