name: Build and Push Docker Images

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push shared build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build.Dockerfile
          push: true
          tags: ghcr.io/solociti/struxt-build:build

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: server.Dockerfile
          push: true
          tags: ghcr.io/solociti/struxt:${{ github.event.release.tag_name }},ghcr.io/solociti/struxt:latest

      - name: Build and push puppeteer Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: puppeteer.Dockerfile
          push: true
          tags: ghcr.io/solociti/struxt-puppeteer:${{ github.event.release.tag_name }},ghcr.io/solociti/struxt-puppeteer:latest


      - name: Build and push Keycloak Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./keycloak
          file: ./keycloak/keycloak.Dockerfile
          push: true
          tags: ghcr.io/solociti/struxt-keycloak:${{ github.event.release.tag_name }},ghcr.io/solociti/struxt-keycloak:latest
